### ISSUE TITLE
How can I create a combined version graph for multi-module projects?

### ISSUE THREAD

**Issue by liebichw** [jrudolph/sbt-dependency-graph#87] opened 2016-01-15 12:48 UTC
I'm managing a multi-module project, where the root project only aggregates the sub-projects.
When creating a graph, the graph for the root project is empty - is it possible to change that so that
the root graph for a project aggregating child projects consists of the union of the partial graphs?

This is nice if we want to view everything in one picture.

Also the dependencyStats table would profit from such an "aggregate output for aggregated projects" option - we could have one big table showing all dependencies/libraries in one table.

Is this possible?

**Comment by jrudolph** [comment] 2016-01-18 08:32
This is a duplicate of #9. I agree that this would be useful but I haven't yet figured out how to aggregate graphs from aggregated projects.

**Closed by jrudolph** 2016-01-18 08:32 UTC
