### ISSUE TITLE
Cache problems with sbt 0.13.7

### ISSUE THREAD

**Issue by Sciss** [jrudolph/sbt-dependency-graph#58] opened 2014-12-05 23:35 UTC
I'm trying to run `dependency-dot` on my project [Mellite](https://github.com/Sciss/Mellite/tree/b7a6669017b5ac35321bfd482545bf9b70c1c62d). If I change `project/build.properties` from 0.13.6 to 0.13.7, I get the following error:

```
[success] Total time: 1 s, completed Dec 6, 2014 12:31:47 AM
[info] Updating {file:/home/hhrutz/Documents/devel/Mellite/}mellite-core...
[info] Updating {file:/home/hhrutz/Documents/devel/Mellite/}mellite-core...
[info] Resolving com.github.scopt#scopt_2.11;3.2.0 ...
[info] Done updating.
[info] Resolving com.github.scopt#scopt_2.11;3.2.0 ...
[info] Updating {file:/home/hhrutz/Documents/devel/Mellite/}mellite-views...
[info] Updating {file:/home/hhrutz/Documents/devel/Mellite/}mellite-views...
[info] Done updating.
[info] Resolving de.sciss#numbers_2.11;0.1.1 ...
[info] Wrote dependency graph to '/home/hhrutz/Documents/devel/Mellite/core/target/dependencies-compile.dot'
[info] Resolving de.sciss#weblaf-ui;1.28 ...
[info] Done updating.
[info] Resolving de.sciss#weblaf-ui;1.28 ...
[info] Done updating.
[info] Updating {file:/home/hhrutz/Documents/devel/Mellite/}mellite...
[info] Resolving de.sciss#weblaf-ui;1.28 ...
[info] Done updating.
[info] Wrote dependency graph to '/home/hhrutz/Documents/devel/Mellite/target/dependencies-compile.dot'
java.io.FileNotFoundException: /home/hhrutz/Documents/devel/Mellite/views/target/resolution-cache/reports/de.sciss-mellite-views_2.11-compile.xml (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at scala.io.Source$.fromFile(Source.scala:90)
	at scala.io.Source$.fromFile(Source.scala:75)
	at scala.io.Source$.fromFile(Source.scala:53)
	at net.virtualvoid.sbt.graph.IvyGraphMLDependencies$.buildDoc(IvyGraphMLDependencies.scala:224)
	at net.virtualvoid.sbt.graph.IvyGraphMLDependencies$.graph(IvyGraphMLDependencies.scala:70)
	at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$2.apply(Plugin.scala:89)
	at net.virtualvoid.sbt.graph.Plugin$$anonfun$ivyReportForConfig$2.apply(Plugin.scala:89)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (mellite-views/compile:moduleGraph) java.io.FileNotFoundException: /home/hhrutz/Documents/devel/Mellite/views/target/resolution-cache/reports/de.sciss-mellite-views_2.11-compile.xml (No such file or directory)
[error] Total time: 9 s, completed Dec 6, 2014 12:31:57 AM
```

I don't know if this is a bug of sbt or sbt-dependency-graph. Given that 0.13.7 claims to have improved caching, my guess is the former, but perhaps you can take a look at this issue.

**Comment by japgolly** [comment] 2015-02-10 07:35
+1

**Comment by jrudolph** [comment] 2015-02-10 11:55
This seems to happen non-deterministically and only when aggregating from the root project. Can you confirm this?

I guess what happens is that the aggregation runs the report concurrently for all aggregated projects. The report always forces a dependency resolution. If one of the projects depends on another then another dependency resolution may be transitively triggered so that while the report is trying to access the result of the first run, the concurrent run deletes or rewrites the xml file at the same time.

A workaround would be not to aggregate the dependency reports for now. In the future, the real solution would be not to depend on the xml files at all but directly work on the ivy/sbt dependency data structures.

**Comment by japgolly** [comment] 2015-02-10 22:58
I didn't realise it was non-deterministic because every time I ran it, it failed. If I have to switch modules and run it a few times, well that sucks but it's a workaround.

FYI: I was consistently getting this error on a non-aggregate module in my project. On your advice I just ran it a few times in the root modules *and then* switched to a (non-aggregate) sub-module and it worked. Thanks for the advice :)

**Comment by japgolly** [comment] 2015-02-10 23:01
I spoke too soon, it seems about 8 of my 13 modules still refuse to work *at all*. I tried a bunch of permutations of `clean`, module switching and `dependencyTree`.

**Comment by jrudolph** [comment] 2015-02-11 08:57
Ok, I only checked the example from @Sciss which seemed to be non-deterministic. 

@japgolly Do you have an example project I can try?

**Comment by japgolly** [comment] 2015-02-11 09:59
I believe this should do it. ↓
https://github.com/japgolly/sbt/tree/skeleton

**Comment by jrudolph** [comment] 2015-02-11 10:06
Hmm... for me it seems to be non-deterministic when running in the root aggregate but worked for all the submodules I randomly tried. Can you post a console log which I can try to reproduce?

**Comment by japgolly** [comment] 2015-02-11 11:00
Really? Hmmm, sorry, I'll take another look and report back to you with
something replicateable.​

**Comment by BardurArantsson** [comment] 2015-05-21 09:23
I have a project where I'm seeing non-deterministic spurious failures of this type, i.e. the failure is the same, but it's usually a different set of projects that fail from run to run.

(Unfortunately I'm not at liberty to share the code. Is there some way I could provide "anonymized" logs or something which would be useful in debugging this?)

**Comment by jrudolph** [comment] 2015-11-16 17:13
I'm closing this as a duplicate of #39. I guess a lot of the uncertainty of the whether and why this happens is because of the non-determinism which e.g. may have changed between some sbt version.

**Closed by jrudolph** 2015-11-16 17:13 UTC
Labels: Bug
