### ISSUE TITLE
Plugin hangs with particular project

### ISSUE THREAD

**Issue by Sciss** [jrudolph/sbt-dependency-graph#56] opened 2014-09-07 00:38 UTC
I am trying to build the graph for [this project](https://github.com/Sciss/ScalaColliderSwing).

E.g. using the current tag v1.19.0:

    > project scalacolliderswing-app
    > dependency-graph --force

It just heats the CPU but never completes.

**Comment by jrudolph** [comment] 2015-11-16 17:11
Closing as a duplicate of #19.

**Closed by jrudolph** 2015-11-16 17:11 UTC
Labels: Bug
