### ISSUE TITLE
whatDependsOn is not working

### ISSUE THREAD

**Issue by Dirk-c-Walter** [jrudolph/sbt-dependency-graph#95] opened 2016-03-31 16:09 UTC
> sbt whatDependsOn org.slf4j slf4j-api 1.6.1
> [info] Loading global plugins from /home/dirk/.sbt/0.13/plugins
> [info] Loading project definition from /home/dirk/XXX
> [info] Set current project to XXX (in build XXX)
> [error] Not a valid command: whatDependsOn
> [error] Expected whitespace character
> [error] whatDependsOn
> [error]

**Comment by jrudolph** [comment] 2016-04-13 06:34
You need to put quotes around a single command if you aren't calling it from the sbt shell. Try 

```
sbt "whatDependsOn org.slf4j slf4j-api 1.6.1"
```

**Comment by ndelaforge** [comment] 2017-12-23 12:29
This didn't work for me : 

`addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")`

`sbt "whatDependsOn joda-time joda-time 2.9.9"`

```
[error] Expected whitespace character
[error] Expected 'com.mnemotix'
[error] Expected 'org.scala-lang'
[error] Expected 'com.rabbitmq'
[error] Expected 'com.typesafe.akka'
[error] Expected 'com.typesafe'
[error] Expected 'org.scala-lang.modules'
[error] Expected 'org.reactivestreams'
[error] Expected 'com.typesafe.scala-logging'
[error] Expected 'org.slf4j'
[error] Expected 'default'
[error] whatDependsOn joda-time joda-time 2.9.9
```

**Comment by mattfeury** [comment] 2018-08-15 04:37
i am seeing the same error on 0.9.1 (the latest) on sbt 0.13

**Comment by jrudolph** [comment] 2018-08-15 06:47
Can you try if 

```
sbt dependencyTree "whatDependsOn joda-time joda-time 2.9.9"
```

would work?

**Comment by mattfeury** [comment] 2018-08-15 13:51
that command is just running dependencyTree for me and then erroring out on the whatDependsOn:

```
[info]   +-org.apache.commons:commons-imaging:1.0-SNAPSHOT
[info]   +-org.slf4j:slf4j-api:1.7.25
[info]   +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.25)
[info]   
[success] Total time: 1 s, completed Aug 15, 2018 9:50:12 AM
[error] Expected ID character
[error] Not a valid command: whatDependsOn
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Expected '::'
[error] Expected end of input.
[error] No dependencies found
[error] whatDependsOn joda-time joda-time 2.9.9
[error]              ^
```

wrapping the entire sbt command in a string (`sbt "dependencyTree whatDependsOn joda-time joda-time 2.9.9"`) also produces that error:
```
[error] Expected ID character
[error] Not a valid command: dependencyTree
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Expected '::'
[error] Expected end of input.
[error] dependencyTree whatDependsOn joda-time joda-time 2.9.9
```

**Comment by pshirshov** [comment] 2018-08-22 20:13
Why did you close this? It's still the same

**Comment by jrudolph** [comment] 2018-08-23 14:15
Does the same happen if you go into sbt first and then run the command?

```
sbt

> dependencyTree

...

> whatDependsOn ...
```

If someone could post a reproduction project I could look further into it.

**Comment by jrudolph** [comment] 2018-08-23 14:35
I think I've found a potential cause.

**Comment by pshirshov** [comment] 2018-08-23 18:00
> Does the same happen if you go into sbt first and then run the command?
Yeah, I never had it working since you made version optional

**Closed** 2018-08-23 20:14 UTC
Labels: Documentation

**Comment by pshirshov** [comment] 2018-08-23 20:48
Thank you for solving. What about a small release?

**Comment by mattfeury** [comment] 2018-08-28 20:47
working great now. thanks so much!
